version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: server_database_chat_core
    environment:
      POSTGRES_PASSWORD: chat_core
      POSTGRES_USER: chat_core
      POSTGRES_DB: chat_core
    networks:
      - application
  application_chat_core:
    build: .
    container_name: application_chat_core
    networks:
      - application
    ports:
      - "8080:8080"

networks:
  application:
